Express notes api - Jeff Kwon
Jykwon24/m2-0122-code-solutions pull request #33
Opened 2022-03-23 03:54 UTC by Jykwon24

https://recordit.co/p9eF2EIBAb

2022-03-23 04:07 UTC, TimelikeClosure requested changes

2022-03-23 04:07 UTC, TimelikeClosure commented on express-notes-api/index.js
> +      res.status(200).json(dataArray);
When is `!data.notes[key]` going to be `true` here?

2022-03-23 04:07 UTC, TimelikeClosure commented on express-notes-api/index.js
> +});
Performing a `GET /api/notes` multiple times in a row should always produce the same output.

2022-03-23 04:07 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).send({ error: 'id must be a positive integer' });
A `400 Bad Request` should also trigger if the id is:
- A non-positive number
- A non-integer number

2022-03-23 04:10 UTC, Jykwon24 commented on express-notes-api/index.js
> +      res.status(200).json(dataArray);
If the data.json file has no properties in data.notes?

2022-03-25 01:49 UTC, TimelikeClosure requested changes

2022-03-25 01:49 UTC, TimelikeClosure commented on express-notes-api/index.js
> +      res.status(200).json(dataArray);
Even if `data.notes` contains an empty object, that condition will be `false`, meaning `res.status(200).json(dataArray);` will never run:

---

![image](https://user-images.githubusercontent.com/16143771/160038251-26fc54c2-355c-47d0-b057-85e04d8f0d0b.png)

2022-03-25 01:49 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).send({ error: 'id must be a positive integer' });
Requests like `GET /api/notes/45.123` (not an integer) and `GET /api/notes/0` (not positive) should also result in a `400 Bad Request` response. Test requests like these to verify they produce the desired output.

2022-03-25 02:33 UTC, TimelikeClosure requested changes

2022-03-25 02:33 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  res.status(400).send({ error: 'id must be a positive integer' });
Calling `res.send(...)` doesn't end the middleware function, so it's possible that `send` will be called three times on one request. Please make sure there is exactly one response sent for any given request.

2022-03-25 02:33 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).send({ error: 'id must be a positive integer' });
Like the `GET` middleware further up, any `id` which isn't a positive integer should trigger a `400 Bad Request` response: https://en.wikipedia.org/wiki/Natural_number

2022-03-25 03:42 UTC, TimelikeClosure requested changes
@Jykwon24 Almost there, just missed one validation.

2022-03-25 03:42 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).send({ error: 'id must be a postive integer' });
This one should enforce positive integers as well.

2022-03-25 03:53 UTC, TimelikeClosure approved these changes

2022-03-25 03:53 UTC, merged